#!/bin/env bash

# Initial print variables
print1=off
print2=off
print3=off
print4=off
print5=off
print6=off
print7=off
print8=off
print9=off
header='Move No'
headercheck='Move No'

dialog_cancel=1
dialog_esc=255
csv='~/Documents/price_database/08_10_2020.csv'
title="Price Filter"


# create a clear extra button that clears all the variables that has been set6 in current session
clear_all(){
  unset out1
  unset out2
  unset out3
  unset out4
  unset out5
  print1=off
  print2=off
  print3=off
  print4=off
  print5=off
  print6=off
  print7=off
  print8=off
  print9=off
  pstatus1=0
  pstatus2=0
  pstatus3=0
  pstatus4=0
  pstatus5=0
  pstatus6=0
  pstatus7=0
  pstatus8=0
  pstatus9=0
  printing=""
  prevprint=
  header='Move No'
  awk_output=""
  prints=""
  unset main1
  unset main2
  unset main3
  unset main4
  unset main5
  unset query1
  unset query2
  unset query3
  unset query4
  unset query5
  unset herelast
}
clear_2(){
  out2=""
  unset main2
  unset query2
}
clear_3(){
  out3=""
  unset main3
  unset query3
}
clear_4(){
  out4=""
  unset main4
  unset query4
}
clear_5(){
  out5=""
  unset main5
  unset query5
}
# basically makes them all become "" again
file_print(){
  echo ""
  echo "#+BEGIN_SRC awk :in-file $csv :exports results"
  echo 'BEGIN {FS=","'
  echo "print \"$header\"}"
  echo "$out1 $out2 $out3 {print NR$printing}"
  echo "#+END_SRC"
}
custom_query(){
  for i in "${!main1[@]}" "${!main2[@]}" "${!main3[@]}" "${!main4[@]}" "${!main5[@]}"; do
    case "${i}" in
      1)
        case ${main1[$i]} in
          1)
            out1='$3 ~ "F[0-9]"'
            query1="HTF move is a Fib";;
          2)
            out1='$3 ~ /H*TF/'
            query1="HTF move is a H(n)TF move, before a reversal";;
          3)
            out1='$3 ~ /\/R|R$|\w R|R\//'
            query1="HTF move is a Reversal";;
          4)
            out1='$3 ~ "RB"'
            query1="HTF move is a Reversal Breakout";;
        esac
        case ${main2[$i]} in
          1)
            out2='&& $3 ~ "F[0-9]"'
            query2="HTF move is a Fib";;
          2)
            out2='&& $3 ~ /H*TF/'
            query2="HTF move is a H(n)TF move, before a reversal";;
          3)
            out2='&& $3 ~ /\/R|R$|\w R|R\//'
            query2="HTF move is a Reversal";;
          4)
            out2='&& $3 ~ "RB"'
            query2="HTF move is a Reversal Breakout";;
        esac
        case ${main3[$i]} in
          1)
            out3='&& $3 ~ "F[0-9]"'
            query3="HTF move is a Fib";;
          2)
            out3='&& $3 ~ /H*TF/'
            query3="HTF move is a H(n)TF move, before a reversal";;
          3)
            out3='&& $3 ~ /\/R|R$|\w R|R\//'
            query3="HTF move is a Reversal";;
          4)
            out3='&& $3 ~ "RB"'
            query3="HTF move is a Reversal Breakout";;
        esac
        case ${main4[$i]} in
          1)
            out4='&& $3 ~ "F[0-9]"'
            query4="HTF move is a Fib";;
          2)
            out4='&& $3 ~ /H*TF/'
            query4="HTF move is a H(n)TF move, before a reversal";;
          3)
            out4='&& $3 ~ /\/R|R$|\w R|R\//'
            query4="HTF move is a Reversal";;
          4)
            out4='&& $3 ~ "RB"'
            query4="HTF move is a Reversal Breakout";;
        esac
        case ${main5[$i]} in
          1)
            out5='&& $3 ~ "F[0-9]"'
            query5="HTF move is a Fib";;
          2)
            out5='&& $3 ~ /H*TF/'
            query5="HTF move is a H(n)TF move, before a reversal";;
          3)
            out5='&& $3 ~ /\/R|R$|\w R|R\//'
            query5="HTF move is a Reversal";;
          4)
            out5='&& $3 ~ "RB"'
            query5="HTF move is a Reversal Breakout";;
        esac;;
      2)
        case ${main1[$i]} in
          1)
            out1='$4 == "WM"'
            query1="HTF move - With Move";;
          2)
            out1='$4 == "WM-FM"'
            query1="HTF move - With move, First Move";;
          3)
            out1='$4 == "OM"'
            query1="HTF move - Opposite Move";;
        esac
        case ${main2[$i]} in
          1)
            out2='&& $4 == "WM"'
            query2="HTF move - With Move";;
          2)
            out2='&& $4 == "WM-FM"'
            query2="HTF move - With move, First Move";;
          3)
            out2='&& $4 == "OM"'
            query2="HTF move - Opposite Move";;
        esac
        case ${main3[$i]} in
          1)
            out3='&& $4 == "WM"'
            query3="HTF move - With Move";;
          2)
            out3='&& $4 == "WM-FM"'
            query3="HTF move - With move, First Move";;
          3)
            out3='&& $4 == "OM"'
            query3="HTF move - Opposite Move";;
        esac
        case ${main4[$i]} in
          1)
            out4='&& $4 == "WM"'
            query4="HTF move - With Move";;
          2)
            out4='&& $4 == "WM-FM"'
            query4="HTF move - With move, First Move";;
          3)
            out4='&& $4 == "OM"'
            query4="HTF move - Opposite Move";;
        esac
        case ${main5[$i]} in
          1)
            out5='&& $4 == "WM"'
            query5="HTF move - With Move";;
          2)
            out5='&& $4 == "WM-FM"'
            query5="HTF move - With move, First Move";;
          3)
            out5='&& $4 == "OM"'
            query5="HTF move - Opposite Move";;
        esac;;
      3)
        case ${main1[$i]} in
          1)
            out1='$5 ~ "^F[0-9]"'
            query1="Previous move - FB";;
          2)
            out1='$5 ~ "^F[0-9][0-9]%$"'
            query1="Previous move - FB Exclusively";;
          3)
            out1='$5 ~ "H"'
            query1="Previous move - H(n)TF move (Before Reversal)";;
          4)
            out1='$5 ~ "H\w* F"'
            query1="Previous move - H(n)TF FB (Before Reversal)";;
          5)
            out1='$5 ~ "^H\w* F"'
            query1="Previous move - H(n)TF FB (Before Reversal) - Exclusively";;
          6)
            out1='$5 ~ "H\w* R"'
            query1="Previous move - H(n)TF R (Before TTF Reversal)";;
          7)
            out1='$5 ~ "^H\w* R"'
            query1="Previous move - H(n)TF R (Before TTF Reversal) - Exclusively";;
          8)
            out1='$5 ~ /\/R|R$|\w R|R\//'
            query1="Previous move - Reversal";;
          9)
            out1='$5 ~ /^R$/'
            query1="Previous move - Reversal - Exclusviely";;
          10)
            out1='$5 ~ "RB"'
            query1="Previous move - Reversal Breakout";;
          11)
            out1='$5 ~ "^RB$"'
            query1="Previous move - Reversal Breakout - Exclusively";;
        esac
        case ${main2[$i]} in
          1)
            out2='&& $5 ~ "^F[0-9]"'
            query2="Previous move - FB";;
          2)
            out2='&& $5 ~ "^F[0-9][0-9]%$"'
            query2="Previous move - FB Exclusively";;
          3)
            out2='&& $5 ~ "H"'
            query2="Previous move - H(n)TF move (Before Reversal)";;
          4)
            out2='&& $5 ~ "H\w* F"'
            query2="Previous move - H(n)TF FB (Before Reversal)";;
          5)
            out2='&& $5 ~ "^H\w* F"'
            query2="Previous move - H(n)TF FB (Before Reversal) - Exclusively";;
          6)
            out2='&& $5 ~ "H\w* R"'
            query2="Previous move - H(n)TF R (Before TTF Reversal)";;
          7)
            out2='&& $5 ~ "^H\w* R"'
            query2="Previous move - H(n)TF R (Before TTF Reversal) - Exclusively";;
          8)
            out2='&& $5 ~ /\/R|R$|\w R|R\//'
            query2="Previous move - Reversal";;
          9)
            out2='&& $5 ~ /^R$/'
            query2="Previous move - Reversal - Exclusviely";;
          10)
            out2='&& $5 ~ "RB"'
            query2="Previous move - Reversal Breakout";;
          11)
            out2='&& $5 ~ "^RB$"'
            query2="Previous move - Reversal Breakout - Exclusively";;
        esac
        case ${main3[$i]} in
          1)
            out3='&& $5 ~ "^F[0-9]"'
            query3="Previous move - FB";;
          2)
            out3='&& $5 ~ "^F[0-9][0-9]%$"'
            query3="Previous move - FB Exclusively";;
          3)
            out3='&& $5 ~ "H"'
            query3="Previous move - H(n)TF move (Before Reversal)";;
          4)
            out3='&& $5 ~ "H\w* F"'
            query3="Previous move - H(n)TF FB (Before Reversal)";;
          5)
            out3='&& $5 ~ "^H\w* F"'
            query3="Previous move - H(n)TF FB (Before Reversal) - Exclusively";;
          6)
            out3='&& $5 ~ "H\w* R"'
            query3="Previous move - H(n)TF R (Before TTF Reversal)";;
          7)
            out3='&& $5 ~ "^H\w* R"'
            query3="Previous move - H(n)TF R (Before TTF Reversal) - Exclusively";;
          8)
            out3='&& $5 ~ /\/R|R$|\w R|R\//'
            query3="Previous move - Reversal";;
          9)
            out3='&& $5 ~ /^R$/'
            query3="Previous move - Reversal - Exclusviely";;
          10)
            out3='&& $5 ~ "RB"'
            query3="Previous move - Reversal Breakout";;
          11)
            out3='&& $5 ~ "^RB$"'
            query3="Previous move - Reversal Breakout - Exclusively";;
        esac
        case ${main4[$i]} in
          1)
            out4='&& $5 ~ "^F[0-9]"'
            query4="Previous move - FB";;
          2)
            out4='&& $5 ~ "^F[0-9][0-9]%$"'
            query4="Previous move - FB Exclusively";;
          3)
            out4='&& $5 ~ "H"'
            query4="Previous move - H(n)TF move (Before Reversal)";;
          4)
            out4='&& $5 ~ "H\w* F"'
            query4="Previous move - H(n)TF FB (Before Reversal)";;
          5)
            out4='&& $5 ~ "^H\w* F"'
            query4="Previous move - H(n)TF FB (Before Reversal) - Exclusively";;
          6)
            out4='&& $5 ~ "H\w* R"'
            query4="Previous move - H(n)TF R (Before TTF Reversal)";;
          7)
            out4='&& $5 ~ "^H\w* R"'
            query4="Previous move - H(n)TF R (Before TTF Reversal) - Exclusively";;
          8)
            out4='&& $5 ~ /\/R|R$|\w R|R\//'
            query4="Previous move - Reversal";;
          9)
            out4='&& $5 ~ /^R$/'
            query4="Previous move - Reversal - Exclusviely";;
          10)
            out4='&& $5 ~ "RB"'
            query4="Previous move - Reversal Breakout";;
          11)
            out4='&& $5 ~ "^RB$"'
            query4="Previous move - Reversal Breakout - Exclusively";;
        esac
        case ${main5[$i]} in
          1)
            out5='&& $5 ~ "^F[0-9]"'
            query5="Previous move - FB";;
          2)
            out5='&& $5 ~ "^F[0-9][0-9]%$"'
            query5="Previous move - FB Exclusively";;
          3)
            out5='&& $5 ~ "H"'
            query5="Previous move - H(n)TF move (Before Reversal)";;
          4)
            out5='&& $5 ~ "H\w* F"'
            query5="Previous move - H(n)TF FB (Before Reversal)";;
          5)
            out5='&& $5 ~ "^H\w* F"'
            query5="Previous move - H(n)TF FB (Before Reversal) - Exclusively";;
          6)
            out5='&& $5 ~ "H\w* R"'
            query5="Previous move - H(n)TF R (Before TTF Reversal)";;
          7)
            out5='&& $5 ~ "^H\w* R"'
            query5="Previous move - H(n)TF R (Before TTF Reversal) - Exclusively";;
          8)
            out5='&& $5 ~ /\/R|R$|\w R|R\//'
            query5="Previous move - Reversal";;
          9)
            out5='&& $5 ~ /^R$/'
            query5="Previous move - Reversal - Exclusviely";;
          10)
            out5='&& $5 ~ "RB"'
            query5="Previous move - Reversal Breakout";;
          11)
            out5='&& $5 ~ "^RB$"'
            query5="Previous move - Reversal Breakout - Exclusively";;
        esac;;
      4)
        case ${main1[$i]} in
          1)
            out1='$6 ~ /^F[0-9].%/'
            query1="Previous move start line - TTF Fib";;
          2)
            out1='$6 ~ /^F[0-9].%$/'
            query1="Previous move start line - TTF Fib Exclusively";;
          3)
            out1='$6 ~ "synonymous"'
            query1="Previous move start line - TTF Fib Synonymous";;
          4)
            out1='$6 ~ /^F[0-9].% /'
            query1="Previous move start line - TTF Fib at H(n)TF line";;
          5)
            out1='$6 ~ /^[SS|RR]/'
            query1="Previous move start line - TTF S/R";;
          6)
            out1='$6 ~ /^SS$|^RR$/'
            query1="Previous move start line - TTF S/R Exclusively";;
          7)
            out1='$6 ~ /H\w* F/'
            query1="Previous move start line - H(n)TF Fib";;
          8)
            out1='$6 ~ /^H\w* F[0-9].%$/'
            query1="Previous move start line - H(n)TF Fib Exclusively";;
          9)
            out1='$6 ~ /H\w* [SS|RR]/'
            query1="Previous move start line - H(n)TF S/R";;
          10)
            out1='^$6 ~ /H\w* [SS|RR]/'
            query1="Previous move start line - H(n)TF S/R Exclusively";;
        esac
        case ${main2[$i]} in
          1)
            out2='&& $6 ~ /^F[0-9].%/'
            query2="Previous move start line - TTF Fib";;
          2)
            out2='&& $6 ~ /^F[0-9].%$/'
            query2="Previous move start line - TTF Fib Exclusively";;
          3)
            out2='&& $6 ~ "synonymous"'
            query2="Previous move start line - TTF Fib Synonymous";;
          4)
            out2='&& $6 ~ /^F[0-9].% /'
            query2="Previous move start line - TTF Fib at H(n)TF line";;
          5)
            out2='&& $6 ~ /^[SS|RR]/'
            query2="Previous move start line - TTF S/R";;
          6)
            out2='&& $6 ~ /^SS$|^RR$/'
            query2="Previous move start line - TTF S/R Exclusively";;
          7)
            out2='&& $6 ~ /H\w* F/'
            query2="Previous move start line - H(n)TF Fib";;
          8)
            out2='&& $6 ~ /^H\w* F[0-9].%$/'
            query2="Previous move start line - H(n)TF Fib Exclusively";;
          9)
            out2='&& $6 ~ /H\w* [SS|RR]/'
            query2="Previous move start line - H(n)TF S/R";;
          10)
            out2='&& ^$6 ~ /H\w* [SS|RR]/'
            query2="Previous move start line - H(n)TF S/R Exclusively";;
        esac
        case ${main3[$i]} in
          1)
            out3='&& $6 ~ /^F[0-9].%/'
            query3="Previous move start line - TTF Fib";;
          2)
            out3='&& $6 ~ /^F[0-9].%$/'
            query3="Previous move start line - TTF Fib Exclusively";;
          3)
            out3='&& $6 ~ "synonymous"'
            query3="Previous move start line - TTF Fib Synonymous";;
          4)
            out3='&& $6 ~ /^F[0-9].% /'
            query3="Previous move start line - TTF Fib at H(n)TF line";;
          5)
            out3='&& $6 ~ /^[SS|RR]/'
            query3="Previous move start line - TTF S/R";;
          6)
            out3='&& $6 ~ /^SS$|^RR$/'
            query3="Previous move start line - TTF S/R Exclusively";;
          7)
            out3='&& $6 ~ /H\w* F/'
            query3="Previous move start line - H(n)TF Fib";;
          8)
            out3='&& $6 ~ /^H\w* F[0-9].%$/'
            query3="Previous move start line - H(n)TF Fib Exclusively";;
          9)
            out3='&& $6 ~ /H\w* [SS|RR]/'
            query3="Previous move start line - H(n)TF S/R";;
          10)
            out3='&& ^$6 ~ /H\w* [SS|RR]/'
            query3="Previous move start line - H(n)TF S/R Exclusively";;
        esac
        case ${main4[$i]} in
          1)
            out4='&& $6 ~ /^F[0-9].%/'
            query4="Previous move start line - TTF Fib";;
          2)
            out4='&& $6 ~ /^F[0-9].%$/'
            query4="Previous move start line - TTF Fib Exclusively";;
          3)
            out4='&& $6 ~ "synonymous"'
            query4="Previous move start line - TTF Fib Synonymous";;
          4)
            out4='&& $6 ~ /^F[0-9].% /'
            query4="Previous move start line - TTF Fib at H(n)TF line";;
          5)
            out4='&& $6 ~ /^[SS|RR]/'
            query4="Previous move start line - TTF S/R";;
          6)
            out4='&& $6 ~ /^SS$|^RR$/'
            query4="Previous move start line - TTF S/R Exclusively";;
          7)
            out4='&& $6 ~ /H\w* F/'
            query4="Previous move start line - H(n)TF Fib";;
          8)
            out4='&& $6 ~ /^H\w* F[0-9].%$/'
            query4="Previous move start line - H(n)TF Fib Exclusively";;
          9)
            out4='&& $6 ~ /H\w* [SS|RR]/'
            query4="Previous move start line - H(n)TF S/R";;
          10)
            out4='&& ^$6 ~ /H\w* [SS|RR]/'
            query4="Previous move start line - H(n)TF S/R Exclusively";;
        esac
        case ${main5[$i]} in
          1)
            out5='&& $6 ~ /^F[0-9].%/'
            query5="Previous move start line - TTF Fib";;
          2)
            out5='&& $6 ~ /^F[0-9].%$/'
            query5="Previous move start line - TTF Fib Exclusively";;
          3)
            out5='&& $6 ~ "synonymous"'
            query5="Previous move start line - TTF Fib Synonymous";;
          4)
            out5='&& $6 ~ /^F[0-9].% /'
            query5="Previous move start line - TTF Fib at H(n)TF line";;
          5)
            out5='&& $6 ~ /^[SS|RR]/'
            query5="Previous move start line - TTF S/R";;
          6)
            out5='&& $6 ~ /^SS$|^RR$/'
            query5="Previous move start line - TTF S/R Exclusively";;
          7)
            out5='&& $6 ~ /H\w* F/'
            query5="Previous move start line - H(n)TF Fib";;
          8)
            out5='&& $6 ~ /^H\w* F[0-9].%$/'
            query5="Previous move start line - H(n)TF Fib Exclusively";;
          9)
            out5='&& $6 ~ /H\w* [SS|RR]/'
            query5="Previous move start line - H(n)TF S/R";;
          10)
            out5='&& ^$6 ~ /H\w* [SS|RR]/'
            query5="Previous move start line - H(n)TF S/R Exclusively";;
        esac;;
      5)
        case ${main1[$i]} in
          1)
            out1='$7 ~ /^no$|^no -/'
            query1="Previous move did not Over/Undershoot";;
          2)
            out1='$7 ~ /^yes$|^yes -/'
            query1="Previous move did Over or Undershoot";;
          3)
            out1='$7 ~ /^yes -.*overshot/'
            query1="Previous move Overshot";;
          4)
            out1='$7 ~ /^yes -.*undershot/'
            query1="Previous move Undershot";;
          5)
            out1='$7 ~ /^no\/yes/'
            query1="Previous move Over/Undershoot? No and Yes";;
        esac
        case ${main2[$i]} in
          1)
            out2='&& $7 ~ /^no$|^no -/'
            query2="Previous move did not Over/Undershoot";;
          2)
            out2='&& $7 ~ /^yes$|^yes -/'
            query2="Previous move did Over or Undershoot";;
          3)
            out2='&& $7 ~ /^yes -.*overshot/'
            query2="Previous move Overshot";;
          4)
            out2='&& $7 ~ /^yes -.*undershot/'
            query2="Previous move Undershot";;
          5)
            out2='&& $7 ~ /^no\/yes/'
            query2="Previous move Over/Undershoot? No and Yes";;
        esac
        case ${main3[$i]} in
          1)
            out3='&& $7 ~ /^no$|^no -/'
            query3="Previous move did not Over/Undershoot";;
          2)
            out3='&& $7 ~ /^yes$|^yes -/'
            query3="Previous move did Over or Undershoot";;
          3)
            out3='&& $7 ~ /^yes -.*overshot/'
            query3="Previous move Overshot";;
          4)
            out3='&& $7 ~ /^yes -.*undershot/'
            query3="Previous move Undershot";;
          5)
            out3='&& $7 ~ /^no\/yes/'
            query3="Previous move Over/Undershoot? No and Yes";;
        esac
        case ${main4[$i]} in
          1)
            out4='&& $7 ~ /^no$|^no -/'
            query4="Previous move did not Over/Undershoot";;
          2)
            out4='&& $7 ~ /^yes$|^yes -/'
            query4="Previous move did Over or Undershoot";;
          3)
            out4='&& $7 ~ /^yes -.*overshot/'
            query4="Previous move Overshot";;
          4)
            out4='&& $7 ~ /^yes -.*undershot/'
            query4="Previous move Undershot";;
          5)
            out4='&& $7 ~ /^no\/yes/'
            query4="Previous move Over/Undershoot? No and Yes";;
        esac
        case ${main5[$i]} in
          1)
            out5='&& $7 ~ /^no$|^no -/'
            query5="Previous move did not Over/Undershoot";;
          2)
            out5='&& $7 ~ /^yes$|^yes -/'
            query5="Previous move did Over or Undershoot";;
          3)
            out5='&& $7 ~ /^yes -.*overshot/'
            query5="Previous move Overshot";;
          4)
            out5='&& $7 ~ /^yes -.*undershot/'
            query5="Previous move Undershot";;
          5)
            out5='&& $7 ~ /^no\/yes/'
            query5="Previous move Over/Undershoot? No and Yes";;
        esac;;
      6)
        case ${main1[$i]} in
          1)
            out1='$8 ~ "^F[0-9]"'
            query1="This move - FB";;
          2)
            out1='$8 ~ "^F[0-9][0-9]%$"'
            query1="This move - FB Exclusively";;
          3)
            out1='$8 ~ "H"'
            query1=" move - H(n)TFThis move (Before Reversal)";;
          4)
            out1='$8 ~ "H\w* F"'
            query1="This move - H(n)TF FB (Before Reversal)";;
          5)
            out1='$8 ~ "^H\w* F"'
            query1="This move - H(n)TF FB (Before Reversal) - Exclusively";;
          6)
            out1='$8 ~ "H\w* R"'
            query1="This move - H(n)TF R (Before TTF Reversal)";;
          7)
            out1='$8 ~ "^H\w* R"'
            query1="This move - H(n)TF R (Before TTF Reversal) - Exclusively";;
          8)
            out1='$8 ~ /\/R|R$|\w R|R\//'
            query1="This move - Reversal";;
          9)
            out1='$8 ~ /^R$/'
            query1="This move - Reversal - Exclusviely";;
          10)
            out1='$8 ~ "RB"'
            query1="This move - Reversal Breakout";;
          11)
            out1='$8 ~ "^RB$"'
            query1="This move - Reversal Breakout - Exclusively";;
        esac
        case ${main2[$i]} in
          1)
            out2='&& $8 ~ "^F[0-9]"'
            query2="This move - FB";;
          2)
            out2='&& $8 ~ "^F[0-9][0-9]%$"'
            query2="This move - FB Exclusively";;
          3)
            out2='&& $8 ~ "H"'
            query2=" move - H(n)TFThis move (Before Reversal)";;
          4)
            out2='&& $8 ~ "H\w* F"'
            query2="This move - H(n)TF FB (Before Reversal)";;
          5)
            out2='&& $8 ~ "^H\w* F"'
            query2="This move - H(n)TF FB (Before Reversal) - Exclusively";;
          6)
            out2='&& $8 ~ "H\w* R"'
            query2="This move - H(n)TF R (Before TTF Reversal)";;
          7)
            out2='&& $8 ~ "^H\w* R"'
            query2="This move - H(n)TF R (Before TTF Reversal) - Exclusively";;
          8)
            out2='&& $8 ~ /\/R|R$|\w R|R\//'
            query2="This move - Reversal";;
          9)
            out2='&& $8 ~ /^R$/'
            query2="This move - Reversal - Exclusviely";;
          10)
            out2='&& $8 ~ "RB"'
            query2="This move - Reversal Breakout";;
          11)
            out2='&& $8 ~ "^RB$"'
            query2="This move - Reversal Breakout - Exclusively";;
        esac
        case ${main3[$i]} in
          1)
            out3='&& $8 ~ "^F[0-9]"'
            query3="This move - FB";;
          2)
            out3='&& $8 ~ "^F[0-9][0-9]%$"'
            query3="This move - FB Exclusively";;
          3)
            out3='&& $8 ~ "H"'
            query3=" move - H(n)TFThis move (Before Reversal)";;
          4)
            out3='&& $8 ~ "H\w* F"'
            query3="This move - H(n)TF FB (Before Reversal)";;
          5)
            out3='&& $8 ~ "^H\w* F"'
            query3="This move - H(n)TF FB (Before Reversal) - Exclusively";;
          6)
            out3='&& $8 ~ "H\w* R"'
            query3="This move - H(n)TF R (Before TTF Reversal)";;
          7)
            out3='&& $8 ~ "^H\w* R"'
            query3="This move - H(n)TF R (Before TTF Reversal) - Exclusively";;
          8)
            out3='&& $8 ~ /\/R|R$|\w R|R\//'
            query3="This move - Reversal";;
          9)
            out3='&& $8 ~ /^R$/'
            query3="This move - Reversal - Exclusviely";;
          10)
            out3='&& $8 ~ "RB"'
            query3="This move - Reversal Breakout";;
          11)
            out3='&& $8 ~ "^RB$"'
            query3="This move - Reversal Breakout - Exclusively";;
        esac
        case ${main4[$i]} in
          1)
            out4='&& $8 ~ "^F[0-9]"'
            query4="This move - FB";;
          2)
            out4='&& $8 ~ "^F[0-9][0-9]%$"'
            query4="This move - FB Exclusively";;
          3)
            out4='&& $8 ~ "H"'
            query4=" move - H(n)TFThis move (Before Reversal)";;
          4)
            out4='&& $8 ~ "H\w* F"'
            query4="This move - H(n)TF FB (Before Reversal)";;
          5)
            out4='&& $8 ~ "^H\w* F"'
            query4="This move - H(n)TF FB (Before Reversal) - Exclusively";;
          6)
            out4='&& $8 ~ "H\w* R"'
            query4="This move - H(n)TF R (Before TTF Reversal)";;
          7)
            out4='&& $8 ~ "^H\w* R"'
            query4="This move - H(n)TF R (Before TTF Reversal) - Exclusively";;
          8)
            out4='&& $8 ~ /\/R|R$|\w R|R\//'
            query4="This move - Reversal";;
          9)
            out4='&& $8 ~ /^R$/'
            query4="This move - Reversal - Exclusviely";;
          10)
            out4='&& $8 ~ "RB"'
            query4="This move - Reversal Breakout";;
          11)
            out4='&& $8 ~ "^RB$"'
            query4="This move - Reversal Breakout - Exclusively";;
        esac
        case ${main5[$i]} in
          1)
            out5='&& $8 ~ "^F[0-9]"'
            query5="This move - FB";;
          2)
            out5='&& $8 ~ "^F[0-9][0-9]%$"'
            query5="This move - FB Exclusively";;
          3)
            out5='&& $8 ~ "H"'
            query5=" move - H(n)TFThis move (Before Reversal)";;
          4)
            out5='&& $8 ~ "H\w* F"'
            query5="This move - H(n)TF FB (Before Reversal)";;
          5)
            out5='&& $8 ~ "^H\w* F"'
            query5="This move - H(n)TF FB (Before Reversal) - Exclusively";;
          6)
            out5='&& $8 ~ "H\w* R"'
            query5="This move - H(n)TF R (Before TTF Reversal)";;
          7)
            out5='&& $8 ~ "^H\w* R"'
            query5="This move - H(n)TF R (Before TTF Reversal) - Exclusively";;
          8)
            out5='&& $8 ~ /\/R|R$|\w R|R\//'
            query5="This move - Reversal";;
          9)
            out5='&& $8 ~ /^R$/'
            query5="This move - Reversal - Exclusviely";;
          10)
            out5='&& $8 ~ "RB"'
            query5="This move - Reversal Breakout";;
          11)
            out5='&& $8 ~ "^RB$"'
            query5="This move - Reversal Breakout - Exclusively";;
        esac;;
      7)
        case ${main1[$i]} in
          1)
            out1='$9 ~ /^F/'
            query1="This move start line - TTF Fib";;
          2)
            out1='$9 ~ /^F[0-9].%$/'
            query1="This move start line - TTF Fib Exclusively";;
          3)
            out1='$9 ~ "synonymous"'
            query1="This move start line - TTF Fib Synonymous";;
          4)
            out1='$6 ~ /^F[0-9].% /'
            query1="This move start line - TTF Fib at H(n)TF line";;
          5)
            out1='$9 ~ /^[SS|RR]/'
            query1="This move start line - TTF S/R";;
          6)
            out1='$9 ~ /^SS$|^RR$/'
            query1="This move start line - TTF S/R Exclusively";;
          7)
            out1='$9 ~ /H\w* F/'
            query1="This move start line - H(n)TF Fib";;
          8)
            out1='$9 ~ /^H\w* F/'
            query1="This move start line - H(n)TF Fib Exclusively";;
          9)
            out1='$9 ~ /H\w* [SS|RR]/'
            query1="This move start line - H(n)TF S/R";;
          10)
            out1='$9 ~ /^H\w* [SS|RR]/'
            query1="This move start line - H(n)TF S/R Exclusively";;
        esac
        case ${main2[$i]} in
          1)
            out2='&& $9 ~ /^F/'
            query2="This move start line - TTF Fib";;
          2)
            out2='&& $9 ~ /^F[0-9].%$/'
            query2="This move start line - TTF Fib Exclusively";;
          3)
            out2='&& $9 ~ "synonymous"'
            query2="This move start line - TTF Fib Synonymous";;
          4)
            out2='$6 ~ /^F[0-9].% /'
            query2="This move start line - TTF Fib at H(n)TF line";;
          5)
            out2='&& $9 ~ /^[SS|RR]/'
            query2="This move start line - TTF S/R";;
          6)
            out2='&& $9 ~ /^SS$|^RR$/'
            query2="This move start line - TTF S/R Exclusively";;
          7)
            out2='&& $9 ~ /H\w* F/'
            query2="This move start line - H(n)TF Fib";;
          8)
            out2='&& $9 ~ /^H\w* F/'
            query2="This move start line - H(n)TF Fib Exclusively";;
          9)
            out2='&& $9 ~ /H\w* [SS|RR]/'
            query2="This move start line - H(n)TF S/R";;
          10)
            out2='&& $9 ~ /^H\w* [SS|RR]/'
            query2="This move start line - H(n)TF S/R Exclusively";;
        esac
        case ${main3[$i]} in
          1)
            out3='&& $9 ~ /^F/'
            query3="This move start line - TTF Fib";;
          2)
            out3='&& $9 ~ /^F[0-9].%$/'
            query3="This move start line - TTF Fib Exclusively";;
          3)
            out3='&& $9 ~ "synonymous"'
            query3="This move start line - TTF Fib Synonymous";;
          4)
            out3='$6 ~ /^F[0-9].% /'
            query3="This move start line - TTF Fib at H(n)TF line";;
          5)
            out3='&& $9 ~ /^[SS|RR]/'
            query3="This move start line - TTF S/R";;
          6)
            out3='&& $9 ~ /^SS$|^RR$/'
            query3="This move start line - TTF S/R Exclusively";;
          7)
            out3='&& $9 ~ /H\w* F/'
            query3="This move start line - H(n)TF Fib";;
          8)
            out3='&& $9 ~ /^H\w* F/'
            query3="This move start line - H(n)TF Fib Exclusively";;
          9)
            out3='&& $9 ~ /H\w* [SS|RR]/'
            query3="This move start line - H(n)TF S/R";;
          10)
            out3='&& $9 ~ /^H\w* [SS|RR]/'
            query3="This move start line - H(n)TF S/R Exclusively";;
        esac
        case ${main4[$i]} in
          1)
            out4='&& $9 ~ /^F/'
            query4="This move start line - TTF Fib";;
          2)
            out4='&& $9 ~ /^F[0-9].%$/'
            query4="This move start line - TTF Fib Exclusively";;
          3)
            out4='&& $9 ~ "synonymous"'
            query4="This move start line - TTF Fib Synonymous";;
          4)
            out4='$6 ~ /^F[0-9].% /'
            query4="This move start line - TTF Fib at H(n)TF line";;
          5)
            out4='&& $9 ~ /^[SS|RR]/'
            query4="This move start line - TTF S/R";;
          6)
            out4='&& $9 ~ /^SS$|^RR$/'
            query4="This move start line - TTF S/R Exclusively";;
          7)
            out4='&& $9 ~ /H\w* F/'
            query4="This move start line - H(n)TF Fib";;
          8)
            out4='&& $9 ~ /^H\w* F/'
            query4="This move start line - H(n)TF Fib Exclusively";;
          9)
            out4='&& $9 ~ /H\w* [SS|RR]/'
            query4="This move start line - H(n)TF S/R";;
          10)
            out4='&& $9 ~ /^H\w* [SS|RR]/'
            query4="This move start line - H(n)TF S/R Exclusively";;
        esac
        case ${main5[$i]} in
          1)
            out5='&& $9 ~ /^F/'
            query5="This move start line - TTF Fib";;
          2)
            out5='&& $9 ~ /^F[0-9].%$/'
            query5="This move start line - TTF Fib Exclusively";;
          3)
            out5='&& $9 ~ "synonymous"'
            query5="This move start line - TTF Fib Synonymous";;
          4)
            out5='$6 ~ /^F[0-9].% /'
            query5="This move start line - TTF Fib at H(n)TF line";;
          5)
            out5='&& $9 ~ /^[SS|RR]/'
            query5="This move start line - TTF S/R";;
          6)
            out5='&& $9 ~ /^SS$|^RR$/'
            query5="This move start line - TTF S/R Exclusively";;
          7)
            out5='&& $9 ~ /H\w* F/'
            query5="This move start line - H(n)TF Fib";;
          8)
            out5='&& $9 ~ /^H\w* F/'
            query5="This move start line - H(n)TF Fib Exclusively";;
          9)
            out5='&& $9 ~ /H\w* [SS|RR]/'
            query5="This move start line - H(n)TF S/R";;
          10)
            out5='&& $9 ~ /^H\w* [SS|RR]/'
            query5="This move start line - H(n)TF S/R Exclusively";;
        esac;;
      8)
        case ${main1[$i]} in
          1)
            out1='$10 ~ /^no$|^no -/'
            query1="This move did not Over/Undershoot";;
          2)
            out1='$10 ~ /^yes$|^yes -/'
            query1="This move did Over or Undershoot";;
          3)
            out1='$10 ~ /^yes -.*overshot/'
            query1="This move Overshot";;
          4)
            out1='$10 ~ /^yes -.*undershot/'
            query1="This move Undershot";;
          5)
            out1='$10 ~ /^no\/yes/'
            query1="This move Over/Undershoot? No and Yes";;
        esac
        case ${main2[$i]} in
          1)
            out2='&& $10 ~ /^no$|^no -/'
            query2="This move did not Over/Undershoot";;
          2)
            out2='&& $10 ~ /^yes$|^yes -/'
            query2="This move did Over or Undershoot";;
          3)
            out2='&& $10 ~ /^yes -.*overshot/'
            query2="This move Overshot";;
          4)
            out2='&& $10 ~ /^yes -.*undershot/'
            query2="This move Undershot";;
          5)
            out2='&& $10 ~ /^no\/yes/'
            query2="This move Over/Undershoot? No and Yes";;
        esac
        case ${main3[$i]} in
          1)
            out3='&& $10 ~ /^no$|^no -/'
            query3="This move did not Over/Undershoot";;
          2)
            out3='&& $10 ~ /^yes$|^yes -/'
            query3="This move did Over or Undershoot";;
          3)
            out3='&& $10 ~ /^yes -.*overshot/'
            query3="This move Overshot";;
          4)
            out3='&& $10 ~ /^yes -.*undershot/'
            query3="This move Undershot";;
          5)
            out3='&& $10 ~ /^no\/yes/'
            query3="This move Over/Undershoot? No and Yes";;
        esac
        case ${main4[$i]} in
          1)
            out4='&& $10 ~ /^no$|^no -/'
            query4="This move did not Over/Undershoot";;
          2)
            out4='&& $10 ~ /^yes$|^yes -/'
            query4="This move did Over or Undershoot";;
          3)
            out4='&& $10 ~ /^yes -.*overshot/'
            query4="This move Overshot";;
          4)
            out4='&& $10 ~ /^yes -.*undershot/'
            query4="This move Undershot";;
          5)
            out4='&& $10 ~ /^no\/yes/'
            query4="This move Over/Undershoot? No and Yes";;
        esac
        case ${main5[$i]} in
          1)
            out5='&& $10 ~ /^no$|^no -/'
            query5="This move did not Over/Undershoot";;
          2)
            out5='&& $10 ~ /^yes$|^yes -/'
            query5="This move did Over or Undershoot";;
          3)
            out5='&& $10 ~ /^yes -.*overshot/'
            query5="This move Overshot";;
          4)
            out5='&& $10 ~ /^yes -.*undershot/'
            query5="This move Undershot";;
          5)
            out5='&& $10 ~ /^no\/yes/'
            query5="This move Over/Undershoot? No and Yes";;
        esac;;
      9)
        case ${main1[$i]} in
          1)
            out1='$11 ~ /^OS/'
            query1="LTF reversed with One Swing";;
          2)
            out1='$11 ~ /^OS - R$/'
            query1="LTF reversed with One Swing - Reversal";;
          3)
            out1='$11 ~ /^OS - RB/'
            query1="LTF reversed with One Swing - Reversal Breakout";;
          4)
            out1='$11 ~ /^DT|^DB/'
            query1="LTF reversed with DB/DT";;
          5)
            out1='$11 ~ /^HDT|^HDB/'
            query1="LTF reversed with HDB/HDT";;
          6)
            out1='$11 ~ /^QDB|^QDT/'
            query1="LTF reversed with QDB/QDT";;
        esac
        case ${main2[$i]} in
          1)
            out2='&& $11 ~ /^OS/'
            query2="LTF reversed with One Swing";;
          2)
            out2='&& $11 ~ /^OS - R$/'
            query2="LTF reversed with One Swing - Reversal";;
          3)
            out2='&& $11 ~ /^OS - RB/'
            query2="LTF reversed with One Swing - Reversal Breakout";;
          4)
            out2='&& $11 ~ /^DT|^DB/'
            query2="LTF reversed with DB/DT";;
          5)
            out2='&& $11 ~ /^HDT|^HDB/'
            query2="LTF reversed with HDB/HDT";;
          6)
            out2='&& $11 ~ /^QDB|^QDT/'
            query2="LTF reversed with QDB/QDT";;
        esac
        case ${main3[$i]} in
          1)
            out3='&& $11 ~ /^OS/'
            query3="LTF reversed with One Swing";;
          2)
            out3='&& $11 ~ /^OS - R$/'
            query3="LTF reversed with One Swing - Reversal";;
          3)
            out3='&& $11 ~ /^OS - RB/'
            query3="LTF reversed with One Swing - Reversal Breakout";;
          4)
            out3='&& $11 ~ /^DT|^DB/'
            query3="LTF reversed with DB/DT";;
          5)
            out3='&& $11 ~ /^HDT|^HDB/'
            query3="LTF reversed with HDB/HDT";;
          6)
            out3='&& $11 ~ /^QDB|^QDT/'
            query3="LTF reversed with QDB/QDT";;
        esac
        case ${main4[$i]} in
          1)
            out4='&& $11 ~ /^OS/'
            query4="LTF reversed with One Swing";;
          2)
            out4='&& $11 ~ /^OS - R$/'
            query4="LTF reversed with One Swing - Reversal";;
          3)
            out4='&& $11 ~ /^OS - RB/'
            query4="LTF reversed with One Swing - Reversal Breakout";;
          4)
            out4='&& $11 ~ /^DT|^DB/'
            query4="LTF reversed with DB/DT";;
          5)
            out4='&& $11 ~ /^HDT|^HDB/'
            query4="LTF reversed with HDB/HDT";;
          6)
            out4='&& $11 ~ /^QDB|^QDT/'
            query4="LTF reversed with QDB/QDT";;
        esac
        case ${main5[$i]} in
          1)
            out5='&& $11 ~ /^OS/'
            query5="LTF reversed with One Swing";;
          2)
            out5='&& $11 ~ /^OS - R$/'
            query5="LTF reversed with One Swing - Reversal";;
          3)
            out5='&& $11 ~ /^OS - RB/'
            query5="LTF reversed with One Swing - Reversal Breakout";;
          4)
            out5='&& $11 ~ /^DT|^DB/'
            query5="LTF reversed with DB/DT";;
          5)
            out5='&& $11 ~ /^HDT|^HDB/'
            query5="LTF reversed with HDB/HDT";;
          6)
            out5='&& $11 ~ /^QDB|^QDT/'
            query5="LTF reversed with QDB/QDT";;
        esac;;
    esac
  done
}
fieldt() {
  case $fields in
    1)
      field_title="What HTF move is this move in?"
      ;;
    2)
      field_title="What is this moves direction in realtion to the HTF move?"
      ;;
    3)
      field_title="What is the previous move on this TF"
      ;;
    4)
      field_title="What line did the Previous move son this TF start from?"
      ;;
    5)
      field_title="Did the start of the previous move over/undershoot?"
      ;;
    6)
      field_title="What move is this move?"
      ;;
    7)
      field_title="What line did this move start from?"
      ;;
    8)
      field_title="Did the start of this move over/undershoot?"
      ;;
    9)
      field_title="How did the beginning of this move reverse on the LTF?"
  esac
}

#trying to allow the default print to change with the selection of prints
status_set(){
  if [ $pstatus1 = 1 ]; then
  print1=on
  pstatus1=0
    else print1=off
  fi

  if [ $pstatus2 = 1 ]; then
  print2=on
  pstatus2=0
    else print2=off
  fi

  if [ $pstatus3 = 1 ]; then
  print3=on
  pstatus3=0
    else print3=off
  fi

  if [ $pstatus4 = 1 ]; then
  print4=on
  pstatus4=0
    else print4=off
  fi

  if [ $pstatus5 = 1 ]; then
  print5=on
  pstatus5=0
    else print5=off
  fi

  if [ $pstatus6 = 1 ]; then
  print6=on
  pstatus6=0
    else print6=off
  fi

  if [ $pstatus7 = 1 ]; then
  print7=on
  pstatus7=0
    else print7=off
  fi

  if [ $pstatus8 = 1 ]; then
  print8=on
  pstatus8=0
    else print8=off
  fi

  if [ $pstatus9 = 1 ]; then
  print9=on
  pstatus9=0
    else print9=off
  fi
}
status_check_mini(){
  if [ $prevprint ==  ]; then
  print_default
  fi
}
status_check(){
  if [ $prevprint == yes ]; then
  status_set
  fi
}
print_default(){
  if [ ${#main1[@]} -gt 0 ]; then
    case ${!main1[@]} in
      1)
        print1=on
        ;;
      2)
        print2=on
        ;;
      3)
        print3=on
        ;;
      4)
        print4=on
        ;;
      5)
        print5=on
        ;;
      6)
        print6=on
        ;;
      7)
        print7=on
        ;;
      8)
        print8=on
        ;;
      9)
        print9=on
        ;;
    esac
  fi 

  if [ ${#main2[@]} -gt 0 ]; then
    case ${!main2[@]} in
      1)
        print1=on
        ;;
      2)
        print2=on
        ;;
      3)
        print3=on
        ;;
      4)
        print4=on
        ;;
      5)
        print5=on
        ;;
      6)
        print6=on
        ;;
      7)
        print7=on
        ;;
      8)
        print8=on
        ;;
      9)
        print9=on
        ;;
    esac
  fi 

  if [ ${#main3[@]} -gt 0 ]; then
    case ${!main3[@]} in
      1)
        print1=on
        ;;
      2)
        print2=on
        ;;
      3)
        print3=on
        ;;
      4)
        print4=on
        ;;
      5)
        print5=on
        ;;
      6)
        print6=on
        ;;
      7)
        print7=on
        ;;
      8)
        print8=on
        ;;
      9)
        print9=on
        ;;
    esac
  fi 
  if [ ${#main4[@]} -gt 0 ]; then
    case ${!main4[@]} in
      1)
        print1=on
        ;;
      2)
        print2=on
        ;;
      3)
        print3=on
        ;;
      4)
        print4=on
        ;;
      5)
        print5=on
        ;;
      6)
        print6=on
        ;;
      7)
        print7=on
        ;;
      8)
        print8=on
        ;;
      9)
        print9=on
        ;;
    esac
  fi 
  if [ ${#main5[@]} -gt 0 ]; then
    case ${!main5[@]} in
      1)
        print1=on
        ;;
      2)
        print2=on
        ;;
      3)
        print3=on
        ;;
      4)
        print4=on
        ;;
      5)
        print5=on
        ;;
      6)
        print6=on
        ;;
      7)
        print7=on
        ;;
      8)
        print8=on
        ;;
      9)
        print9=on
        ;;
    esac
  fi 
}

what_selected() {
  case $main in
    1)
      unset main1
      main1=([$fields]=$queries);;
    4)
      unset main2
      main2=([$fields]=$queries);;
    7)
      unset main3
      main3=([$fields]=$queries);;
    10)
      unset main4
      main4=([$fields]=$queries);;
    13)
      unset main5
      main5=([$fields]=$queries);;
  esac 
}
query_field() {
    case $fields in
  1)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 "Fib Retracement" \
      2 'H(n)TF move - Before Reversal' \
      3 'Reversal' \
      4 'Reversal Breakout' \
      2>&1 1>&3)
  what_selected
  custom_query
      ;;
  2)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 'With Move' \
      2 'With Move - First Move' \
      3 'Opposite Move' \
      2>&1 1>&3)
  what_selected
  custom_query
      ;;
  3)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 "Fib Retracement" \
      2 "Fib Retracement - Exclusively" \
      3 'H(n)TF move before Reversal' \
      4 'H(n)TF Fib before Reversal' \
      5 'H(n)TF Fib before Reversal - Exclusively' \
      6 'H(n)TF Reversal before TTF Reversal' \
      7 'H(n)TF Reversal before TTF Reversal - Exclusively' \
      8 'Reversal' \
      9 'Reversal - Exclusively' \
      10 'Reversal Breakout' \
      11 'Reversal Breakout - Exclusively' \
      2>&1 1>&3)
  what_selected
  custom_query
      ;;
  4)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 'TTF Fib' \
      2 'TTF Fib - Exclusively' \
      3 'TTF Fib - Synonymous' \
      4 'TTF Fibs at H(n)TF' \
      5 'TTF Support/Resistance' \
      6 'TTF Support/Resistance - Exclusively' \
      7 'H(n)TF Fib' \
      8 'H(n)TF Fib - Exclusively' \
      9 'H(n)TF Support/Resistance' \
      10 'H(n)TF Support/Resistance - Exclusively' \
      2>&1 1>&3)
  what_selected
  custom_query
      ;;
  5)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 'No' \
      2 'Yes' \
      3 'Yes - Overshot' \
      4 'Yes - Undershot' \
      5 'No/Yes' \
      2>&1 1>&3)
  what_selected
  custom_query
      ;;
  6)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 "Fib Retracement" \
      2 "Fib Retracement - Exclusively" \
      3 'H(n)TF move before Reversal' \
      4 'H(n)TF Fib before Reversal' \
      5 'H(n)TF Fib before Reversal - Exclusively' \
      6 'H(n)TF Reversal before TTF Reversal' \
      7 'H(n)TF Reversal before TTF Reversal - Exclusively' \
      8 'Reversal' \
      9 'Reversal - Exclusively' \
      10 'Reversal Breakout' \
      11 'Reversal Breakout - Exclusively' \
      2>&1 1>&3)
  what_selected
  custom_query
      ;;
  7)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 'TTF Fib' \
      2 'TTF Fib - Exclusively' \
      3 'TTF Fib - Synoymous' \
      4 'TTF Fibs at H(n)TF' \
      5 'TTF Support/Resistance' \
      6 'TTF Support/Resistance - Exclusively' \
      7 'H(n)TF Fib' \
      8 'H(n)TF Fib - Exclusively' \
      9 'H(n)TF Support/Resistance' \
      10 'H(n)TF Support/Resistance - Exclusively' \
      2>&1 1>&3)
  what_selected
  custom_query
      ;;
  8)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 'No' \
      2 'Yes' \
      3 'Yes - Overshot' \
      4 'Yes - Undershot' \
      5 'No/Yes' \
      2>&1 1>&3)
  what_selected
  custom_query
      ;;
  9)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 'One Swing' \
      2 'One Swing - Reversal' \
      3 'One Swing - Reversal Breakout' \
      4 'Double Bottom/Top' \
      5 'Half Double Bottom/Top' \
      6 'Quarter Double Bottom/Top' \
      2>&1 1>&3)
  what_selected
  custom_query
      ;;
    esac
}


# ---------- Above section is varaibles and funvtions------------------------------




# Below line makes me input a csv file to read the data
#read -e -p "Hello, Please input the CSV file to be read: " csv

# main page of program
while true; do
  exec 3>&1
  main=$(dialog \
    --backtitle "$title" \
    --title "Menu" \
    --no-tags \
    --default-item "$herelast" \
    --cancel-label "Exit" \
    --extra-button --extra-label "Clear Menu" \
    --menu "Please select:" 0 0 18 \
    1 "First Query" \
    2 "$query1" \
    3 "" \
    4 "Second Query" \
    5 "$query2" \
    6 "" \
    7 "Third Query" \
    8 "$query3" \
    9 "" \
    10 "Fourth Query" \
    11 "$query4" \
    12 "" \
    13 "Fifth Query" \
    14 "$query5" \
    15 "" \
    16 "Print Fields" \
    17 "View" \
    18 "Next Move" \
    2>&1 1>&3)
  # exit statements below 
  case $? in
    1)
      clear
      echo "Hope it was helpful Alex, Till next time I guess :)"
      # testing echos to see what variables are being assigned properly
      echo "$awk_output"
      echo "$out1 $out2 $out3 $out4 $out5"
      echo "$printing"
      echo "$prints"
      echo "$header"
      exit
      ;;
    3)
      clearing=$(dialog \
        --title "$title" \
        --backtitle "clearing menu" \
        --no-tags \
        --cancel-label "Back" \
        --menu "Clearing Menu" 0 0 9 \
        1 "Clear 2nd Query" \
        2 "Clear 3nd Query" \
        3 "Clear 4th Query" \
        4 "Clear 5th Query" \
        5 "Clear All Queries" \
        2>&1 1>&3)
      case $clearing in
        1)
          clear_2
          dialog --sleep 1 \
            --title "$title" \
            --infobox "Cleared 2nd query" 10 52;;
        2)
          clear_3
          dialog --sleep 1 \
            --title "$title" \
            --infobox "Cleared 3rd query" 10 52;;
        3)
          clear_4
          dialog --sleep 1 \
            --title "$title" \
            --infobox "Cleared 4th query" 10 52;;
        4)
          clear_5
          dialog --sleep 1 \
            --title "$title" \
            --infobox "Cleared 5th query" 10 52;;
        5)
          clear_all
          dialog --sleep 1 \
            --title "$title" \
            --infobox "Cleared all queries" 10 52;;
      esac;;
    255)
      clear
      echo "aaaahhh it was helpful Alex, Till next time I guess :)"
      exit
      ;;
  esac
  case $main in
    1)
      fields=$(dialog \
        --backtitle "$title" \
        --title "First Query" \
        --no-tags \
        --cancel-label "Exit" \
        --menu "Please select:" 0 0 9 \
        1 'HTF move this move is in' \
        2 'Direction in relation to HTF move' \
        3 'Previous move on this TF' \
        4 'Line the previous move started from' \
        5 'Did it overshoot or undershoot' \
        6 'What is this move' \
        7 'What line Did it start from' \
        8 'Did it overshoot or undershoot' \
        9 'How did the beginning of this move reverse from the LTF perspective' \
        2>&1 1>&3)
      query_field
      herelast=4
      ;;
    4)
      fields=$(dialog \
        --backtitle "$title" \
        --title "Second Query" \
        --no-tags \
        --cancel-label "Exit" \
        --menu "Please select:" 0 0 9 \
        1 'HTF move this move is in' \
        2 'Direction in relation to HTF move' \
        3 'Previous move on this TF' \
        4 'Line the previous move started from' \
        5 'Did it overshoot or undershoot' \
        6 'What is this move' \
        7 'What line Did it start from' \
        8 'Did it overshoot or undershoot' \
        9 'How did the beginning of this move reverse from the LTF perspective' \
        2>&1 1>&3)
      query_field
      herelast=7
      ;;
    7)
      fields=$(dialog \
        --backtitle "$title" \
        --title "Third Query" \
        --no-tags \
        --cancel-label "Exit" \
        --menu "Please select:" 0 0 9 \
        1 'HTF move this move is in' \
        2 'Direction in relation to HTF move' \
        3 'Previous move on this TF' \
        4 'Line the previous move started from' \
        5 'Did it overshoot or undershoot' \
        6 'What is this move' \
        7 'What line Did it start from' \
        8 'Did it overshoot or undershoot' \
        9 'How did the beginning of this move reverse from the LTF perspective' \
        2>&1 1>&3)
      query_field
      herelast=10
      ;;
    10)
      fields=$(dialog \
        --backtitle "$title" \
        --title "Fourth Query" \
        --no-tags \
        --cancel-label "Exit" \
        --menu "Please select:" 0 0 9 \
        1 'HTF move this move is in' \
        2 'Direction in relation to HTF move' \
        3 'Previous move on this TF' \
        4 'Line the previous move started from' \
        5 'Did it overshoot or undershoot' \
        6 'What is this move' \
        7 'What line Did it start from' \
        8 'Did it overshoot or undershoot' \
        9 'How did the beginning of this move reverse from the LTF perspective' \
        2>&1 1>&3)
      query_field
      herelast=13
      ;;
    13)
      fields=$(dialog \
        --backtitle "$title" \
        --title "Fifth Query" \
        --no-tags \
        --cancel-label "Exit" \
        --menu "Please select:" 0 0 9 \
        1 'HTF move this move is in' \
        2 'Direction in relation to HTF move' \
        3 'Previous move on this TF' \
        4 'Line the previous move started from' \
        5 'Did it overshoot or undershoot' \
        6 'What is this move' \
        7 'What line Did it start from' \
        8 'Did it overshoot or undershoot' \
        9 'How did the beginning of this move reverse from the LTF perspective' \
        2>&1 1>&3)
      query_field
      herelast=16
      ;;
    16)
      status_check_mini
      prints=($(dialog \
        --title "$title" \
        --no-tags \
        --cancel-label "Back" \
        --checklist "Please select:" 0 0 9 \
        1 'HTF Move this move is in' $print1\
        2 'Direction in relation to HTF move' $print2\
        3 'Previous move on this TF' $print3\
        4 'Line the previous move started from' $print4\
        5 'Did it overshoot or undershoot' $print5\
        6 'What is this move' $print6\
        7 'What line Did it start from' $print7\
        8 'Did it overshoot or undershoot' $print8\
        9 'How did the beginning of this move reverse from the LTF perspective' $print9\
        2>&1 1>&3))
      for p in "${prints[@]}"; do
        case "${p}" in
          1)
            pstatus1=1
            printcheck+='"\t"$3'
            headercheck+='\tHTF move';;
          2)
            pstatus2=1
            printcheck+='"\t"$4'
            headercheck+='\tDirection in relation to HTF move';;
          3)
            pstatus3=1
            printcheck+='"\t"$5'
            headercheck+='\tPrevious move';;
          4)
            pstatus4=1
            printcheck+='"\t"$6'
            headercheck+='\tLine previous move started from';;
          5)
            pstatus5=1
            printcheck+='"\t"$7'
            headercheck+='\tPrevious move over/undershoot';;
          6)
            pstatus6=1
            printcheck+='"\t"$8'
            headercheck+='\tThis move';;
          7)
            pstatus7=1
            printcheck+='"\t"$9'
            headercheck+='\tLine this move started from';;
          8)
            pstatus8=1
            printcheck+='"\t"$10'
            headercheck+='\tThis move over/undershoot';;
          9)
            pstatus9=1
            printcheck+='"\t"$11'
            headercheck+='\tLTF reversal pattern';;
        esac
      done
      if [ "$printcheck" != "" ]; then
      printing="$printcheck"
      printcheck=""

      header="$headercheck"
      headercheck='Move No'
      prevprint=yes
      status_check
      pstatus1=0
      pstatus2=0
      pstatus3=0
      pstatus4=0
      pstatus5=0
      pstatus6=0
      pstatus7=0
      pstatus8=0
      pstatus9=0

      herelast=17
      fi
      ;;
    17)
      awk_output=$(awk -F, -v header="$header" \
        "BEGIN {print header} \
        $out1 $out2 $out3 $out4 $out5 {print NR,$printing}" ~/Documents/price_database/08_10_2020.csv)
      dialog --title "$title" \
        --no-collapse \
        --extra-button --extra-label "To-File" \
        --msgbox "$awk_output" 40 180

        if [ $? = 3 ]; then \
          file=$(dialog --title "$title" \
          --fselect ~/Documents/price_database/research/reversalBreakout/ 14 48 2>&1 1>&3)
          if [[ "$file" =~ \.org$ ]]; then
          file_print >> "$file"
          else
            file_print | install -D /dev/stdin "$file.org"
          fi
        fi
        ;;
    18)
      next_print='NR,"\t"$8"\t"$9"\t"$10"\t"$11'
      next_header='Move No\tThis move\tLine this move started from\tThis move over/undershoot\tLTF reversal pattern'
      next_output=$(awk -F, -v next_header="$next_header"\
        "BEGIN {print next_header} \
        $out1 $out2 $out3 $out4 $out5 {getline;print $next_print;}" ~/Documents/price_database/08_10_2020.csv)
      dialog --title "$title" \
        --no-collapse \
        --extra-button --extra-label "To-File" \
        --msgbox "$next_output" 40 180

        if [ $? = 3 ]; then \
          file=$(dialog --title "$title" \
          --fselect ~/Documents/price_database/research/reversalBreakout/ 14 48 2>&1 1>&3)
          if [[ "$file" =~ \.org$ ]]; then
          file_print >> "$file"
          else
            file_print | install -D /dev/stdin "$file.org"
          fi
        fi
        ;;
  esac
done
