#!/bin/env bash

# Initial print variables
print1='off'
print2='off'
print3='off'
print4='off'
print5='off'
print6='off'
print7='off'
print8='off'
print9='off'

dialog_cancel=1
dialog_esc=255
csv='~/Documents/price_database/08_10_2020.csv'
title="Price Filter"

  # For loop that takes the what_selected result
  # and for each variable i in each of the mains,
  # it gets the index number, which is the field, in a case
  # then the corresponding query number changes a awk statement
  # variable by adding its own custom code to the header
  # and query section.
  #
  #Another function is needed that corresponds to print
  #in the main menu.

custom_query(){
  for i in "${!main1[@]}" "${!main2[@]}" "${!main3[@]}"; do
    case "${i}" in
      1)
        case ${main1[$i]} in
          1)
            out1='$3 ~ "F[0-9]"'
          ;;
          2)
            out1='$3 ~ /H*TF/'
          ;;
          3)
            out1='$3 ~ /\/R|R$|\w R|R\//' 
          ;;
          4)
            out1='$3 ~ "RB"' 
          ;;
        esac
        case ${main2[$i]} in
          1)
            out1='$3 ~ "F[0-9]" &&'
          ;;
          2)
            out1='$3 ~ /H*TF/ &&'
          ;;
          3)
            out1='$3 ~ /\/R|R$|\w R|R\// &&' 
          ;;
          4)
            out1='$3 ~ "RB" &&' 
          ;;
        esac
        case ${main3[$i]} in
          1)
            out1='$3 ~ "F[0-9]"'
          ;;
          2)
            out1='$3 ~ /H*TF/'
          ;;
          3)
            out1='$3 ~ /\/R|R$|\w R|R\//' 
          ;;
          4)
            out1='$3 ~ "RB"' 
          ;;
        esac
        ;;
      2)
        case ${[$i]} in
          1)
             
          ;;
          2)

          ;;
          3)

          ;;
        esac
        ;;
      3)
        case ${[$i]} in
          1)
             
          ;;
          2)

          ;;
          3)

          ;;
          4)

          ;;
          5)
             
          ;;
          6)

          ;;
          7)

          ;;
          8)

          ;;
        esac
        ;;
      4)
        case ${[$i]} in
          1)
             
          ;;
          2)

          ;;
          3)

          ;;
          4)

          ;;
          5)
             
          ;;
          6)

          ;;
          7)

          ;;
          8)

          ;;
        esac
        ;;
      5)
        case ${[$i]} in
          1)
             
          ;;
          2)

          ;;
          3)

          ;;
          4)

          ;;
          5)
             
          ;;
        esac
        ;;
      6)
        case ${[$i]} in
          1)
             
          ;;
          2)

          ;;
          3)

          ;;
          4)

          ;;
          5)
             
          ;;
          6)

          ;;
          7)

          ;;
          8)

          ;;
        esac
        ;;
      7)
        case ${[$i]} in
          1)
             
          ;;
          2)

          ;;
          3)

          ;;
          4)

          ;;
          5)
             
          ;;
          6)

          ;;
          7)

          ;;
          8)

          ;;
        esac
        ;;
      8)
        case ${[$i]} in
          1)
             
          ;;
          2)

          ;;
          3)

          ;;
          4)

          ;;
          5)
             
          ;;
        esac
        ;;
      9)
        case ${[$i]} in
          1)
             
          ;;
          2)

          ;;
          3)

          ;;
          4)

          ;;
          5)
             
          ;;
        esac
        ;;
    esac
  done
}
fieldt() {
  case $fields in
    1)
      field_title="What HTF move is this move in?"
      ;;
    2)
      field_title="What is this moves direction in realtion to the HTF move?"
      ;;
    3)
      field_title="What is the previous move on this TF"
      ;;
    4)
      field_title="What line did the Previous move son this TF start from?"
      ;;
    5)
      field_title="Did the start of the previous move over/undershoot?"
      ;;
    6)
      field_title="What move is this move?"
      ;;
    7)
      field_title="What line did this move start from?"
      ;;
    8)
      field_title="Did the start of this move over/undershoot?"
      ;;
    9)
      field_title="How did the beginning of this move reverse on the LTF?"
  esac
}

#while statements will not work for the print_default function
#it creates a endless loop
print_default(){
  if [ ${#main1[@]} -gt 0 ]; then
    case ${!main1[@]} in
      1)
        print1=on
        ;;
      2)
        print2=on
        ;;
      3)
        print3=on
        ;;
      4)
        print4=on
        ;;
      5)
        print5=on
        ;;
      6)
        print6=on
        ;;
      7)
        print7=on
        ;;
      8)
        print8=on
        ;;
      9)
        print9=on
        ;;
    esac
  fi 

  if [ ${#main2[@]} -gt 0 ]; then
    case ${!main2[@]} in
      1)
        print1=on
        ;;
      2)
        print2=on
        ;;
      3)
        print3=on
        ;;
      4)
        print4=on
        ;;
      5)
        print5=on
        ;;
      6)
        print6=on
        ;;
      7)
        print7=on
        ;;
      8)
        print8=on
        ;;
      9)
        print9=on
        ;;
    esac
  fi 

  if [ ${#main3[@]} -gt 0 ]; then
    case ${!main3[@]} in
      1)
        print1=on
        ;;
      2)
        print2=on
        ;;
      3)
        print3=on
        ;;
      4)
        print4=on
        ;;
      5)
        print5=on
        ;;
      6)
        print6=on
        ;;
      7)
        print7=on
        ;;
      8)
        print8=on
        ;;
      9)
        print9=on
        ;;
    esac
  fi 
}
what_selected() {
  case $main in
    1)
      main1=([$fields]=$queries)
      ;;
    2)
      main2=([$fields]=$queries)
      ;;
    3)
      main3=([$fields]=$queries)
      ;;
  esac 
}
query_field() {
    case $fields in
  1)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 "Fib Retracement" \
      2 'H(n)TF move - Before Reversal' \
      3 'Reversal' \
      4 'Reversal Breakout' \
      2>&1 1>&3)
  what_selected
  custom_query
      ;;
  2)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 'With Move' \
      2 'With Move - First Move' \
      3 'Opposite Move' \
      2>&1 1>&3)
  what_selected
      ;;
  3)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 "Fib Retracement" \
      2 "Fib Retracement - Exclusively" \
      3 'H(n)TF move before Reversal' \
      4 'H(n)TF move before Reversal - Exclusively' \
      5 'Reversal' \
      6 'Reversal - Exclusively' \
      7 'Reversal Breakout' \
      8 'Reversal Breakout - Exclusively' \
      2>&1 1>&3)
  what_selected
      ;;
  4)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 'TTF Fib' \
      2 'TTF Fib - Exclusively' \
      3 'TTF Support/Resistance' \
      4 'TTF Support/Resistance - Exclusively' \
      5 'H(n)TF Fib' \
      6 'H(n)TF Fib - Exclusively' \
      7 'H(n)TF Support/Resistance' \
      8 'H(n)TF Support/Resistance - Exclusively' \
      2>&1 1>&3)
  what_selected
      ;;
  5)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 'No' \
      2 'Yes' \
      3 'Yes - Overshot' \
      4 'Yes - Undershot' \
      5 'No/Yes' \
      2>&1 1>&3)
  what_selected
      ;;
  6)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 "Fib Retracement" \
      2 "Fib Retracement - Exclusively" \
      3 'H(n)TF move before Reversal' \
      4 'H(n)TF move before Reversal - Exclusively' \
      5 'Reversal' \
      6 'Reversal - Exclusively' \
      7 'Reversal Breakout' \
      8 'Reversal Breakout - Exclusively' \
      2>&1 1>&3)
  what_selected
      ;;
  7)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 'TTF Fib' \
      2 'TTF Fib - Exclusively' \
      3 'TTF Support/Resistance' \
      4 'TTF Support/Resistance - Exclusively' \
      5 'H(n)TF Fib' \
      6 'H(n)TF Fib - Exclusively' \
      7 'H(n)TF Support/Resistance' \
      8 'H(n)TF Support/Resistance - Exclusively' \
      2>&1 1>&3)
  what_selected
      ;;
  8)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 'No' \
      2 'Yes' \
      3 'Yes - Overshot' \
      4 'Yes - Undershot' \
      5 'No/Yes' \
      2>&1 1>&3)
  what_selected
      ;;
  9)
    fieldt
  queries=$(dialog \
    --title "$field_title" \
    --no-tags \
    --backtitle "$title" \
    --cancel-label "Back" \
    --menu "$field_title" 0 0 9 \
      1 'One Swing - Reversal' \
      2 'One Swing - Reversal Breakout' \
      3 'Double Bottom/Top' \
      4 'Half Double Bottom/Top' \
      5 'Quarter Double Bottom/Top' \
      2>&1 1>&3)
  what_selected
      ;;
    esac
}


# ---------- Above section is varaibles and funvtions------------------------------




# Below line makes me input a csv file to read the data
#read -e -p "Hello, Please input the CSV file to be read: " csv

# main page of program
while true; do
  exec 3>&1
  main=$(dialog \
    --backtitle "$title" \
    --title "Menu" \
    --no-tags \
    --cancel-label "Exit" \
    --menu "Please select:" 0 0 9 \
    1 "First Query" \
    2 "Second Query" \
    3 "Third Query" \
    4 "Print Fields" \
    5 "View" \
    2>&1 1>&3)
  # exit statements below 
  case $? in
    1)
      clear
      echo "Hope it was helpful Alex, Till next time I guess :)"
      exit
      ;;
    255)
      clear
      echo "aaaahhh it was helpful Alex, Till next time I guess :)"
      exit
      ;;
  esac
  case $main in
    1)
      fields=$(dialog \
        --backtitle "$title" \
        --title "First Query" \
        --no-tags \
        --cancel-label "Exit" \
        --menu "Please select:" 0 0 9 \
        1 'HTF move this move is in' \
        2 'Direction in relation to HTF move' \
        3 'Previous move on this TF' \
        4 'Line the previous move started from' \
        5 'Did it overshoot or undershoot' \
        6 'What is this move' \
        7 'What line Did it start from' \
        8 'Did it overshoot or undershoot' \
        9 'How did the beginning of this move reverse from the LTF perspective' \
        2>&1 1>&3)
      query_field
      ;;
    2)
      fields=$(dialog \
        --backtitle "$title" \
        --title "Second Query" \
        --no-tags \
        --cancel-label "Exit" \
        --menu "Please select:" 0 0 9 \
        1 'HTF move this move is in' \
        2 'Direction in relation to HTF move' \
        3 'Previous move on this TF' \
        4 'Line the previous move started from' \
        5 'Did it overshoot or undershoot' \
        6 'What is this move' \
        7 'What line Did it start from' \
        8 'Did it overshoot or undershoot' \
        9 'How did the beginning of this move reverse from the LTF perspective' \
        2>&1 1>&3)
      query_field
      ;;
    3)
      fields=$(dialog \
        --backtitle "$title" \
        --title "Third Query" \
        --no-tags \
        --cancel-label "Exit" \
        --menu "Please select:" 0 0 9 \
        1 'HTF move this move is in' \
        2 'Direction in relation to HTF move' \
        3 'Previous move on this TF' \
        4 'Line the previous move started from' \
        5 'Did it overshoot or undershoot' \
        6 'What is this move' \
        7 'What line Did it start from' \
        8 'Did it overshoot or undershoot' \
        9 'How did the beginning of this move reverse from the LTF perspective' \
        2>&1 1>&3)
      query_field
      ;;
    4)
      print_default
      prints=$(dialog \
        --title "$title" \
        --no-tags \
        --cancel-label "Back" \
        --checklist "Please select:" 0 0 9 \
        1 'HTF Move this move is in' $print1\
        2 'Direction in relation to HTF move' $print2\
        3 'Previous move on this TF' $print3\
        4 'Line the previous move started from' $print4\
        5 'Did it overshoot or undershoot' $print5\
        6 'What is this move' $print6\
        7 'What line Did it start from' $print7\
        8 'Did it overshoot or undershoot' $print8\
        9 'How did the beginning of this move reverse from the LTF perspective' $print9\
        2>&1 1>&3)
      ;;
    5)
      dialog --title "$title" \
        --msgbox "$awk_output" 0 0 \
        ;;
  esac
done
